### ISSUE TITLE
Logged in State when loading the page

### ISSUE THREAD

**Issue by nimble-byte** [Desyon/NodeJS#13]
Currently the logged in state is always true when reloading the page independent of the previous state.

**Comment by EricFelix** [comment]
Probably linked to the issue, where the token and username do not update correctly. Causes problems elsewhere too

**Comment by EricFelix** [comment]
Seems to be not linked.
Lessons learned: Don't trust stackoverflow blind. All the method didn't work. Now I just set it to undefined manually... does the job

**Comment by nimble-byte** [comment]
Please close this issue with the next commit

**Comment by EricFelix** [comment]
@Desyon should be fixed, please confirm

**Comment by nimble-byte** [comment]
Can confirm.
